services:
  - type: worker
    name: mdlbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m scdlbot
    repo: https://github.com/sholoomail/mdlbot.git
    branch: master
    envVars:
      - key: BOT_TOKEN 
        sync: false
